# Generated by Django 2.0.2 on 2018-04-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsql', '0002_auto_20180409_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suser',
            name='Sinfo',
        ),
    ]
