# Generated by Django 2.0.2 on 2018-04-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsql', '0003_remove_suser_sinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='Susername',
            field=models.CharField(max_length=10),
        ),
    ]
