# Generated by Django 2.0.2 on 2018-05-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsql', '0008_auto_20180430_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='Suserimage',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
