# Generated by Django 2.0.2 on 2018-06-15 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsql', '0009_suser_suserimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Todoname', models.CharField(max_length=20)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsql.SUser')),
            ],
        ),
    ]
