# Generated by Django 2.0.2 on 2018-06-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsql', '0010_usertodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertodo',
            name='Username',
        ),
        migrations.AddField(
            model_name='usertodo',
            name='TodoUserno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='Todoname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
